### ISSUE TITLE
Search capabilities

### ISSUE THREAD

**Issue by JohnWP8253** [Bootcamp-Projects/collocation-creation#6]
• As a user, I want to search for a word and be able to see its meaning, hear how it's pronounced, see other words with similar meanings, see what other words are used with it, and see how to use it in a sentence.
  ## Acceptance criteria

- [x]   -[] index.html needs a container for the definition - will need div for part of speech, div for definition, div for phonetic script
- [x]   -[] index.html has a search input field (sans submit button) 
- [x]   -[] index.html needs an icon for audio of pronunciation
- [x]   -[] index.html & style.css needs an accordion to expand the synonyms - synonymns will need a placeholder for text
- [x]   -[] index.html & style.css needs an accordion for the collocations - collocations will be a two column list

**Comment by thePROZACH25** [comment]
deleted corpus task
